/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToolType = IDL.Text;
export const Time = IDL.Int;
export const HistoryEntry = IDL.Record({
  'output' : IDL.Text,
  'timestamp' : Time,
  'toolType' : ToolType,
  'input' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearToolHistory' : IDL.Func([ToolType], [], []),
  'getAllRecentHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
  'getRecentToolHistory' : IDL.Func(
      [ToolType],
      [IDL.Vec(HistoryEntry)],
      ['query'],
    ),
  'getUsageStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ToolType, IDL.Nat))],
      ['query'],
    ),
  'saveHistory' : IDL.Func([ToolType, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToolType = IDL.Text;
  const Time = IDL.Int;
  const HistoryEntry = IDL.Record({
    'output' : IDL.Text,
    'timestamp' : Time,
    'toolType' : ToolType,
    'input' : IDL.Text,
  });
  
  return IDL.Service({
    'clearToolHistory' : IDL.Func([ToolType], [], []),
    'getAllRecentHistory' : IDL.Func([], [IDL.Vec(HistoryEntry)], ['query']),
    'getRecentToolHistory' : IDL.Func(
        [ToolType],
        [IDL.Vec(HistoryEntry)],
        ['query'],
      ),
    'getUsageStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ToolType, IDL.Nat))],
        ['query'],
      ),
    'saveHistory' : IDL.Func([ToolType, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };